CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_GPIO_MCP230XX=y

# ============================================================
# Power management
# ============================================================

CONFIG_ZMK_PM_SOFT_OFF=y

# 自動Deep Sleepも有効
CONFIG_ZMK_SLEEP=y

# 通常Idleまで 60秒
CONFIG_ZMK_IDLE_TIMEOUT=60000

# Deep Sleepまで 30分
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# ============================================================
# RGB underglow - SK6812MINI-E x6
# ============================================================

CONFIG_SPI=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# TPS610997のENもRGB ON/OFFに連動
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y

# 無操作時にLEDをOFF
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# 起動時は点灯
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Solid color
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# かなり低輝度から開始
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=5

# Fn+↑↓ 一回あたり5%
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=5

# 最低1%
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=1

# 誤って明るくしすぎないよう最大20%
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=20

CONFIG_ZMK_GPIO_KEY_WAKEUP_TRIGGER=y